{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f67c7633-1688-41c1-8a39-807136707b4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import textwrap\n",
    "from pathlib import Path\n",
    "\n",
    "# -------------------------------------------------\n",
    "# Настройки страницы\n",
    "# -------------------------------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Gender authorship by research areas\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# -------------------------------------------------\n",
    "# Загрузка данных\n",
    "# -------------------------------------------------\n",
    "@st.cache_data(show_spinner=True)\n",
    "def load_data(data_dir: Path):\n",
    "    files = {\n",
    "        2022: \"scimagojr_2022.csv\",\n",
    "        2023: \"scimagojr_2023.csv\",\n",
    "        2024: \"scimagojr_2024.csv\",\n",
    "    }\n",
    "\n",
    "    dfs = []\n",
    "    for year, filename in files.items():\n",
    "        df = pd.read_csv(data_dir / filename, sep=\";\")\n",
    "        df[\"Year\"] = year\n",
    "        dfs.append(df)\n",
    "\n",
    "    df = pd.concat(dfs, ignore_index=True)\n",
    "\n",
    "    # %Female → float\n",
    "    df[\"%Female\"] = (\n",
    "        df[\"%Female\"]\n",
    "        .astype(str)\n",
    "        .str.replace(\",\", \".\", regex=False)\n",
    "        .astype(float)\n",
    "    )\n",
    "\n",
    "    # Areas → explode\n",
    "    df[\"Areas\"] = df[\"Areas\"].str.split(\";\")\n",
    "    df = df.explode(\"Areas\")\n",
    "    df[\"Areas\"] = df[\"Areas\"].str.strip()\n",
    "\n",
    "    # Чистка\n",
    "    df = df.dropna(subset=[\"%Female\", \"Areas\", \"Year\"])\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# -------------------------------------------------\n",
    "# Вспомогательные функции\n",
    "# -------------------------------------------------\n",
    "def wrap_label(label, width=25):\n",
    "    return textwrap.fill(label, width=width)\n",
    "\n",
    "\n",
    "def plot_boxplot_top_areas(df, year, top_n=10):\n",
    "    df_year = df[df[\"Year\"] == year]\n",
    "\n",
    "    top_areas = (\n",
    "        df_year\n",
    "        .groupby(\"Areas\")[\"%Female\"]\n",
    "        .median()\n",
    "        .sort_values(ascending=False)\n",
    "        .head(top_n)\n",
    "        .index\n",
    "    )\n",
    "\n",
    "    df_top = df_year[df_year[\"Areas\"].isin(top_areas)]\n",
    "\n",
    "    grouped, labels = [], []\n",
    "    for area, group in df_top.groupby(\"Areas\"):\n",
    "        grouped.append(group[\"%Female\"].values)\n",
    "        labels.append(wrap_label(area))\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(16, 8), facecolor=\"black\")\n",
    "    ax.set_facecolor(\"black\")\n",
    "\n",
    "    ax.boxplot(\n",
    "        grouped,\n",
    "        labels=labels,\n",
    "        patch_artist=False,\n",
    "        boxprops=dict(color=\"white\"),\n",
    "        whiskerprops=dict(color=\"white\"),\n",
    "        capprops=dict(color=\"white\"),\n",
    "        medianprops=dict(color=\"white\"),\n",
    "        flierprops=dict(\n",
    "            marker=\"o\",\n",
    "            markerfacecolor=\"white\",\n",
    "            markeredgecolor=\"white\",\n",
    "            markersize=4,\n",
    "            alpha=0.8,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "    ax.set_title(\n",
    "        f\"Распределение доли женщин-авторов (%Female)\\n\"\n",
    "        f\"Топ-{top_n} Areas по медиане, {year}\",\n",
    "        color=\"white\",\n",
    "        fontsize=15,\n",
    "    )\n",
    "\n",
    "    ax.tick_params(axis=\"x\", colors=\"white\", rotation=22)\n",
    "    ax.tick_params(axis=\"y\", colors=\"white\")\n",
    "\n",
    "    for spine in ax.spines.values():\n",
    "        spine.set_color(\"white\")\n",
    "\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "    plt.close(fig)\n",
    "\n",
    "\n",
    "def plot_boxplot_by_quartile(df, year, area):\n",
    "    df_area = df[\n",
    "        (df[\"Year\"] == year) &\n",
    "        (df[\"Areas\"] == area)\n",
    "    ]\n",
    "\n",
    "    grouped, labels = [], []\n",
    "    for quartile, group in df_area.groupby(\"SJR Best Quartile\"):\n",
    "        grouped.append(group[\"%Female\"].values)\n",
    "        labels.append(quartile)\n",
    "\n",
    "    if not grouped:\n",
    "        st.info(\"Нет данных для выбранного Area и года.\")\n",
    "        return\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "\n",
    "    ax.boxplot(\n",
    "        grouped,\n",
    "        labels=labels,\n",
    "        patch_artist=True,\n",
    "        boxprops=dict(facecolor=\"lightblue\", color=\"blue\"),\n",
    "        whiskerprops=dict(color=\"blue\"),\n",
    "        capprops=dict(color=\"blue\"),\n",
    "        medianprops=dict(color=\"red\"),\n",
    "        flierprops=dict(\n",
    "            marker=\"o\",\n",
    "            markerfacecolor=\"blue\",\n",
    "            markeredgecolor=\"blue\",\n",
    "            markersize=4,\n",
    "            alpha=0.7,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "    ax.set_title(f\"%Female по квартилям\\n{area}, {year}\")\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "    plt.close(fig)\n",
    "\n",
    "\n",
    "# -------------------------------------------------\n",
    "# Основное приложение\n",
    "# -------------------------------------------------\n",
    "def main():\n",
    "    st.title(\"Анализ доли женщин-авторов по областям исследований\")\n",
    "\n",
    "    data_dir = Path(\"data\")\n",
    "    df = load_data(data_dir)\n",
    "\n",
    "    year = st.selectbox(\"Выберите год\", sorted(df[\"Year\"].unique()))\n",
    "\n",
    "    st.subheader(\"Топ Areas по медиане доли женщин\")\n",
    "    plot_boxplot_top_areas(df, year)\n",
    "\n",
    "    areas_available = sorted(df[df[\"Year\"] == year][\"Areas\"].unique())\n",
    "    selected_area = st.selectbox(\n",
    "        \"Выберите Area для детальной разбивки по квартилям\",\n",
    "        areas_available,\n",
    "    )\n",
    "\n",
    "    st.subheader(f\"Детализация по квартилям: {selected_area}\")\n",
    "    plot_boxplot_by_quartile(df, year, selected_area)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
